services:
  mongodb:
    image: mongo:8
    container_name: nivora-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - nivora-mongodb-data:/data/db

  api:
    build: .
    container_name: nivora-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/nivora-ledger
    depends_on:
      - mongodb

volumes:
  nivora-mongodb-data: